### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by zyc13459930811** [Bioconductor/affy#1]
When I run the code justRMA() ,it shows 
"Error in getCdfInfo(object) : 
  Could not obtain CDF environment, problems encountered:
Specified environment does not contain GenomeWideSNP_6
Library - package genomewidesnp6cdf not installed
Bioconductor - genomewidesnp6cdf not available"

How to solve this problem?

**Comment by vjcitn** [comment]
This is a good question.  I would say that the affy package is not really designed for large SNP arrays, so I would direct you to the crlmm package.  To get a handle on using rma with such an array do
```
BiocManager::install("crlmm")
BiocManager::install('genomewidesnp6Crlmm')
BiocManager::install("hapmapsnp6")
library(crlmm)
example(snprma2)
```
I will raise an issue at support.bioconductor.org indicating this, and I'd recommend that you post further questions there.

**Comment by vjcitn** [comment]
Here it is: https://support.bioconductor.org/p/9152936/

**Comment by zyc13459930811** [comment]
Thank you for your reply!



---- Replied Message ----
| From | Vince ***@***.***> |
| Date | 06/25/2023 05:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Bioconductor/affy] some errors (Issue #1) |

Here it is: https://support.bioconductor.org/p/9152936/
